package pages

var (
	domPaths = getDomPaths()
)

func getDomPaths() map[string]string {
	return map[string]string{
		"login_id":            "username-real",
		"password_id":         "pass-real",
		"login_btn":           "input.button-login",
		"ok":                  "div.buttons > span.btn.btn-primary",
		"nav_logo":            "div.nav_logo",
		"alert_box":           "#weekend-trading-popup > span.weekend-trading-close",
		"add_order":           "#positionsTable > span.open-dialog-icon.svg-icon-holder",
		"dt_no_data":          "span.dataTable-no-data-action",
		"search_box":          "#searchlist > div.searchbox > input[type=text]",
		"result_instrument":   "//*[@id='list-results-instruments']/div/div[3]/div/div/div",
		"close":               "span.orderdialog-close",
		"instrument_name":     "span.instrument-name",
		"widget_message":      "div.widget_message",
		"css_title":           "div.title",
		"css_text":            "div.text",
		"mode-btn":            "div.%s-button",
		"quantity":            "div.quantity-slider-input-wrapper > div.placeholder-input > div.visible-input > input",
		"tradebox_price":      "div.%s-button > div.%s-price", //"div.orderdialog div.tradebox-price-%s",
		"order_info_val":      "span.cfd-order-info-item-value",
		"qty_slider":          "div.quantity-slider > div.horizontalSlider",
		"instrument_init_qty": "div.helper-container > span > span:nth-child(2)",
		"slider_left_arrow":   "div.quantity-slider > span.quantity-slider-left-arrow",
		"slider_right_arrow":  "div.quantity-slider > span.quantity-slider-right-arrow",
		"ls_tp_toggle":        "#limit_stop-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.take-profit-container > div.take-profit-toggle",
		"ls_sl_toggle":        "#limit_stop-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.stop-loss-container > div.stop-loss-toggle",
		"market_tp_toggle":    "#market-order-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.take-profit-container > div.take-profit-toggle",
		"market_sl_toggle":    "#market-order-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.take-profit-container > div.stop-loss-toggle",
		"market_sl_down":      "#market-order-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.stop-loss-container > div.limitstop > div.distance-container > div.distance-spinner > div.spinner-arrow-container > div.spinner-arrow.spinner-down.svg-icon-holder",
		"market_sl_up":        "#market-order-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.stop-loss-container > div.limitstop > div.distance-container > div.distance-spinner > div.spinner-arrow-container > div.spinner-arrow.spinner-up.svg-icon-holder",
		"market_tp_down":      "#market-order-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.take-profit-container > div.limitstop > div.distance-container > div.distance-spinner > div.spinner-arrow-container > div.spinner-arrow.spinner-down.svg-icon-holder",
		"market_tp_up":        "#market-order-profitloss > div.scrollable-area > div.scrollable-area-body > div > div.take-profit-container > div.limitstop > div.distance-container > div.distance-spinner > div.spinner-arrow-container > div.spinner-arrow.spinner-up.svg-icon-holder",
		"confirm_btn":         "div.button-container > div.confirm-button",
		"ok_btn":              "div.buttons > span.btn.btn-primary",
		"tab_positions":       "span.tab-item.tabpositions",
		"tab_orders":          "span.tab-item.taborders",
		"positions_last_row":  "#positionsTable > div.scrollable-area.scrollable-area-at-top > div.scrollable-area-body > div > table > tbody > tr:last-child",
		"orders_last_row":     "#ordersTable > div.scrollable-area.scrollable-area-at-top > div.scrollable-area-body > div > table > tbody > tr:last-child",
		"cxtmenu":             "div.contextmenu",
		"rm_item":             "div.item-%s-contextmenu-remove",
		"date_created":        "#positionsTable > div.dataTable-header > table > thead > tr > th.created",
		"settings":            "#positionsTable > span.column-settings-icon",
		"dt_ctxmenu":          "//*[@id='datatable-contextmenu']",
		"ctx_name":            "div.item.item-datatable-contextmenu-name",
		"ctx_qty":             "div.item.item-datatable-contextmenu-quantity",
		"ctx_dir":             "div.item.item-datatable-contextmenu-direction",
		"ctx_price":           "div.item.item-datatable-contextmenu-averagePrice",
		"ctx_curprice":        "div.item.item-datatable-contextmenu-currentPrice",
		"ctx_tp":              "div.item.item-datatable-contextmenu-limitPrice",
		"ctx_sl":              "div.item.item-datatable-contextmenu-stopPrice",
		"cxt_ts":              "div.item.item-datatable-contextmenu-trailingStop",
		"ctx_margin":          "div.item.item-datatable-contextmenu-margin",
		"ctx_datecreated":     "div.item.item-datatable-contextmenu-created",
		"ctx_result":          "div.item.item-datatable-contextmenu-ppl",
		"name":                "div.header > div.instrument-name",
		"qty":                 "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[2]",
		"direction":           "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[3]",
		"avg_price":           "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[4]",
		"cur_price":           "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[5]",
		"take_profit":         "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[7]",
		"stop_loss":           "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[8]",
		"trailing_stop":       "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[9]",
		"margin":              "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[6]",
		"created":             "//*[@id='position-details']/div/div[3]/div/div/div[2]/div[1]",
		"result":              "td.ppl",
		"info_close":          "div.header > div.close-icon",
		"dlg":                 "div.window",
		"market_order_tab":    "div.scrollable-area-content > div.tab-control > span:nth-child(1)",
		"info_tab":            "div.scrollable-area-content > div.tab-control > span:nth-child(4)",
		"qty_value":           "div.position-quantity-and-price",
		"qty_input_xpath":     "/html/body/div[8]/div[2]/div[3]/div[1]/div[1]/div[3]/div/div[2]/div[3]/div[1]/div[2]/div[2]/input",
		"input_qty_val":       "div.helper-container > span > span:nth-child(2)",
	}
}
